rstudio/pins-python

- docs/api/boards.rst
- pins/boards.py
- pins/drivers.py
- pins/tests/test_boards.py
- pins/tests/test_meta.py
- pins/versions.py
* Implemented `pin_delete`, `pin_version_delete`, `pin_versions_prune`
* Explicitly raise error for user when they try to delete the active RSC bundle
* Simplified things a bit to use fixtures to create pins-to-be-deleted
Note that...
* Note that I xfail'd a test related to #15. This was needed to ensure a version string is returned as a result of `pin_versions`.
* I hacked around the meta created in pin_write, not having the correct version when using the RSC board. (related to above issue)
> feat: implement pin_delete, pin_version_delete

- pins/rsconnect/api.py
* Corrects default RSConnect API Key name from `RSC_CONNECT_API_KEY` to `CONNECT_API_KEY`. This matches what RSConnect uses internally (and R pins behavior).
> fix!: correct rsc env api key name

- .env.dev
- docs/getting_started.Rmd
- pins/boards.py
- pins/cache.py
- pins/config.py
- pins/constructors.py
- pins/drivers.py
- pins/meta.py
- pins/tests/conftest.py
- pins/tests/helpers.py
- pins/tests/test_boards.py
- pins/tests/test_cache.py
- pins/tests/test_compat.py
- pins/tests/test_constructors.py
- requirements/dev.txt
- setup.cfg
Implements a cache that preserves the structure of a pin board. E.g. a file named `<some_pin>/<some_version>/mtcars.csv`, will be nested in its pin and version directory in the cache. This is unusual for the cache, which normally hashes the path and lets fsspec handle where the file is accessed from.
TODO:
* implement `cache_prune`, `cache_info` (#37)
* test all current constructors
* Punt on cache_browse, implement together with pin_browse (#52)
UNANTICIPATED TODO:
* modify BoardManual to handle downloading of single files (#54 ) / add a special cache for it in the process
> feat: basic path preserving cache

- docs/getting_started.Rmd
- pins/boards.py
- pins/config.py
- pins/constructors.py
- pins/drivers.py
- pins/errors.py
- pins/tests/test_boards.py
- pins/tests/test_config.py
Addresses #39 by requiring users to set one of the following (ordered highest to lowest priority):
* allow_insecure_read=True when initializing the board
* the PINS_ALLOW_INSECURE_READ=1 environment variable
TODO:
* document in getting started / the board docstring
* add to board constructors
> feat!: require user to opt-in to read unsafe pins

- pins/__init__.py
- pins/boards.py
- pins/cache.py
- pins/config.py
- pins/constructors.py
- pins/meta.py
- pins/rsconnect/api.py
- pins/tests/test_boards.py
- pins/tests/test_constructors.py
Addresses #75 by updating the access time of a pin's `data.txt` every time it is accessed.
Additional changes:
* replaced print statements with logging (put in `pins.config._enable_logs()` to print logs for now)
* added an RSC specific cache class (fixes user names creating unnecessary nesting in the cache)
> Feat cache touch

- pins/boards.py
- pins/drivers.py
- pins/tests/test_boards.py
- pins/tests/test_drivers.py
Addresses #88, #5 , by using an objects `__qualname__` if it is not a pandas DataFrame. Note that I also fixed the title structure to match R pins: `"<pin_name>: a pinned {more info} {obj_name}"`
> feat: generalize automatic titles

- pins/constructors.py
- pins/tests/test_constructors.py
Addresses #89, e.g.
```python
>>> from pins.constructors import *
>>> board_deparse(board_rsconnect(server_url="http://example.com", api_key="xxx"))
"board_rsconnect(server_url='http://example.com')"
>>> board_deparse(board_folder("a/b/c"))
"board_folder('a/b/c')"
```
Note that currently the RSC approach differs from R:
```R
> board_deparse(board)
board_rsconnect("envvar", server = "https://colorado.rstudio.com/rsc")
```
Let's remedy in #93
> feat: deparse rsc and file boards

- .github/workflows/ci.yml
- Makefile
- pins/__init__.py
- pins/boards.py
- pins/tests/test_cache.py
- setup.cfg
* handle some backward incompatible pieces (e.g. Protocol, shutils.copytree)
* add python versions to test matrix
* note that I removed installing dev.txt requirements, so CI now checks "would a person installing pins right now be able to do these things"
> ci: test across py 3.7 to 3.10

- pins/__init__.py
- pins/boards.py
- pins/constructors.py
- pins/rsconnect/api.py
- pins/rsconnect/fs.py
- pins/tests/test_rsconnect_api.py
- pins/utils.py
Addresses:
* #67 
* Adds ExtendMethodDoc to ensure that child methods include parent docstrings (e.g. a person using `pin_read` will want the full docstring, even if they're using `BoardRsConnect`.
> Feat rsc access type

- .gitignore
- README.Rmd
- README.md
- docs/api/boards.rst
- docs/getting_started.Rmd
- docs/intro.md
This PR refines the docs a bit as we get more eyes on this. 
Do you know why the note box [in this section](https://rstudio.github.io/pins-python/getting_started.html#reading-and-writing-data) generates an error?
> Refine docs + README

- .github/workflows/ci.yml
- pins/constructors.py
- pins/drivers.py
- pins/tests/test_drivers.py
- setup.cfg
This PR 
* adds the storage types "feather" and "parquet", which delegate to pandas.DataFrame.to_parquet/feather, and pandas.read_parquet/feather..!
* skips a test that was hitting the github API, causing rate limit errors
> feat: add support for parquet and arrow storage

- .env.dev
- .github/workflows/ci.yml
- Makefile
- README.md
- docs/api/constructors.rst
- docs/getting_started.Rmd
- pins/__init__.py
- pins/boards.py
- pins/constructors.py
- pins/tests/conftest.py
- pins/tests/helpers.py
- setup.cfg
Implements google cloud storage as a backend.
TODO:
* ~~swap out the siuba-tests project for a dedicated pins one~~ (edit: could take care of when backends are moved in rstudio specific accounts)
* ~~implement a board_gcs constructor~~ (done)
edit: requires #126
> feat(gcs): initial google cloud storage support

- pins/boards.py
- pins/drivers.py
- pins/tests/test_boards.py
- pins/tests/test_drivers.py
- pins/utils.py
> fix: support reading type arrow

- .github/workflows/ci.yml
- pins/rsconnect/api.py
- pins/tests/test_cache.py
- pins/tests/test_constructors.py
Addressing #148, by adding windows to test matrix
Notes:
* Cleans up path tests which were unix specific (e.g. str.split("/") to using pathlib.Path methods)
* Adds a `time.sleep()` call to many cache tests, since there seems to be some kind of windows time/sleep precision related race condition.
* Refactors the way RSC bundle archives are created from using NamedTemporaryFile to TemporaryFolder. I couldn't replicate the original issue in #148 , but feel more confident this won't accidentally clean up the temporary bundle too early.
> ci: add windows to test matrix

- .github/workflows/ci.yml
- docs/api/constructors.rst
- docs/api/index.rst
- docs/getting_started.Rmd
- docs/intro.md
- pins/__init__.py
- pins/constructors.py
- pins/tests/conftest.py
- pins/tests/helpers.py
- pins/tests/test_constructors.py
Initial implementation of azure backend.
TODO:
> feat: azure backend

- docs/api/constructors.rst
- docs/api/index.rst
- pins/__init__.py
- pins/boards.py
- pins/constructors.py
- pins/rsconnect/fs.py
- pins/tests/test_boards.py
* Adds support for reading public RStudio Connect pin content, using `board_manual`.
* Cleans up how board_manual constructs paths to pins.
> feat!: support public rsc pin read, using manual board

- pins/boards.py
addresses #144 by listing out accepted type options. (There may be a better way to let users browse different type saving options down the road, when/if saving pins becomes extensible..)
> docs: list pin type options in pin_write method

- .github/workflows/ci.yml
- .github/workflows/cross-compat.yml
* Move compatibility check into its own workflow
* Adds workflow dispatch input, so you can choose the version of pins-r to install
> ci: move compat check to own job, add workflow dispatch

- docs/api/constructors.rst
- docs/api/index.rst
- docs/getting_started.Rmd
- docs/intro.md
- pins/__init__.py
- pins/constructors.py
- pins/tests/_snapshots/test_board_pin_write_rsc_index_html/index.html
- setup.cfg
> feat: add board_connect for Posit Connect, formerly RStudio

- docs/getting_started.Rmd
Closes #187 
This PR updates the "Getting Started" page to remove some of the leftover R-specific language and for completeness of `type`, etc. You can see the [analogous page for R here](https://pins.rstudio.com/dev/articles/pins.html).
> Update "Getting Started"

- .github/CODE_OF_CONDUCT.md
- LICENSE
- MAINTAINERS.md
- setup.cfg
This PR closes https://github.com/rstudio/pins-python/issues/185. Note that I followed dplyr's license casing, and changed "Pins Python Authors" to "pins-python authors".
> chore: update authors, license, code of conduct

- pins/boards.py
This PR closes open file handles to avoid resource leakage from only accessing the file name.
> fix: close open file handles in `pin_download`

- docs/_quarto.yml
Hi there,
I noticed that there was a wrong link in the website header that led to the Vetiver package. I have fixed it to the Pins-Python package.
Cheers,
Anatoly
> Fixed link to github repo in quarto yaml

- setup.cfg
In `fsspec==2023.9.0`, there are some breaking changes for pins's cache. We will specify which versions are known to work for the next release, and resolve the breaking changes in the subsequent release.
> restrict `fsspec` less than 2023.9.0

- pins/boards.py
- pins/constructors.py
- pins/tests/test_boards.py
- pins/tests/test_constructors.py
Currently, `board_url` is considered read-only without versioning support, but `versioned=True` on creation. This PR moves the NotImplementedError from the creation of any board with the attribute `versioned=False` and instead raises errors on relevant methods that should not be used with a read-only board.
> Set `versioned=False` for `board_url`

- pins/constructors.py
- pins/tests/test_boards.py
closes #205 
add examples of using `board_connect` in scenarios where `CONNECT_SERVER` and `CONNECT_API_KEY` are set as well as when custom envvar names are used.
> docs: add examples with environment variables for `board_connect`

- pins/boards.py
- pins/constructors.py
- pins/rsconnect/html/index.html
- pins/tests/_snapshots/test_board_pin_write_rsc_index_html/index.html
parity to https://github.com/rstudio/pins-r/pull/806/files
on preview in Posit Connect, users should be able to see how to load the data in R and Python if applicable.
> feat: preview r code in connect to read pin

- .github/workflows/ci.yml
- pins/tests/helpers.py
- requirements/minimum.txt
- setup.cfg
Update dependencies in anticipation of supporting more recent versions of python and fsspec
> drop python 3.7 support, min fsspec>=2022.2.0

- docs/get_started.qmd
Related to rstudio/pins-r#817
Based on feedback during a recent pins stakeholder meeting, let's further clarify what and how to write objects/data as pins. I'll also plan to do a PR to the Connect docs with some language like this.
> Update docs with info about concurrent writes

- pins/boards.py
This PR passes `detail=False` to the `ls` method calls in `pins` to allow compatibility with later versions of `fsspec` which have `detail=True` set as the default.
> fix(fsspec): pass `detail=False` to `ls` to continue returning a list of strings

- pins/rsconnect/api.py
Right now, we are using `json.JSONDecodeError`, but depending on Python version, `json.JSONDecodeError`, `simplejson.JSONDecodeError`, `ValueError`, `requests.JSONDecodeError`, or `requests.RequestException`, could be sent from the request. All 5 types are captured by `requests.JSONDecodeError`, so let's use this to give more informative errors.
> use `requests.JSONDecodeError` to catch more requests errors

- pins/__init__.py
- pins/boards.py
- pins/constructors.py
This helps avoid a circular input, as mentioned in this comment:
https://github.com/rstudio/pins-python/blob/41c37aea979d3f09e7c0ef4d8cae40d491b02440/pins/boards.py#L1092
1. I have kept `board_deparse` imported in `pins.constructors` to avoid breaking backward compatibility.
2. The comment recommended moving the function to `pins.utils` but this would not solve the issue of a circular import, since the issue is that the function uses `BaseBoard` in its type annotation from `pins.boards`.
Instead, I have placed the function in `pins.boards`, which I think is sensible since the function accepts board as its only arg.
2. I am not sure whether you value PRs like this. I see TODOs in the code and I assume it is appreciated to resolve them, but I am aware that they are fairly cosmetic in cases …
> Moving board_deparse to boards.py

- pins/boards.py
I noticed a few places in the code where there were workarounds associated with Python 3.7. Since support for 3.7 has been dropped, I have refactored to remove these workarounds.
> Remove syntax used as a workaround while Python 3.7 was being supported

- pins/tests/test_versions.py
- pins/versions.py
> Fix off-by-one error in version parsing function msg.

- pins/boards.py
- pins/meta.py
- pins/versions.py
- pyproject.toml
> Enable "FA" rules in ruff and apply UP rules to migrate syntax

- pins/constructors.py
- pyproject.toml
> Enable reportUnusedExpression in pyright

- docs/get_started.qmd
- pins/boards.py
- pins/tests/test_boards.py
To resolve #241.
I struggled for a while to realize that `prepare_pin_version` deletes the old pin via `version_setup` for unversioned boards. To deal with this, I have pre-emptively retrieved the meta object before it is deleted, and then used that to compare the hash.
I think part of the issue is perhaps that `version_setup` doesn't belong in `pins/versions.py` - I am of the view that it is currently too decontextualized and would be better closer to the place where it is invoked, in `prepare_pin_version`. A docstring would help too.
It's worth noting that this is a breaking change - as a result some of the existing tests needed modifying to opt-in to the old behaviour.
I'm not sure whether the READMEs need any updates. I took a read but I think it would be distracting to detail this …
> Implement `force_identicial_write`

- pins/boards.py
- pins/drivers.py
- pins/meta.py
- pins/rsconnect/api.py
- pins/tests/test_boards.py
- pins/tests/test_drivers.py
- pins/versions.py
closes #314 
closes #311
Allows for multiple file paths to be passed into `pin_upload()`. This will NOT handle directories.
> feat: multifile handling in `pin_upload`/`pin_download`

- pins/rsconnect/api.py
- pyproject.toml
> Enable reportOptionalIterable in pyright

- pins/boards.py
CI is failing (can see in #298) due to this extra /, I think.
> maint: remove extra / in doctest

- .github/workflows/code-checks.yml
As per https://github.com/rstudio/pins-python/actions/runs/14583410776/job/40904471773?pr=327
the version v2.0.3 depends on a deprecated service.
> Bump pre-commit action

- docs/get_started.qmd
> Document how to create a board for a shared network drive with caching
