pins/_types.py, pins/boards.py, pins/drivers.py, pins/meta.py, pins/tests/test_boards.py, pins/tests/test_compat.py, pins/tests/test_meta.py, pins/versions.py
Implements:
* basic object saving via save_data
* basic title creation via default_title
* pin_write over a single object (CSV)
* MetaFactory.create to create meta for pin_write
* Meta serialization methods, e.g. `to_dict()`
* A slew of tests
=> Feat pin write

pins/__init__.py, pins/boards.py, pins/cache.py, pins/config.py, pins/rsconnect/api.py, pins/tests/test_utils.py, pins/utils.py
Addresses
* #48 
* #56 
* #82 
Notes
* Added a `utils.py` module with an `inform()` function, for printing user messages (while also logging).
* Added pins.config.pins_options, which has a `quiet = True` attribute, for deciding whether to print above messages.
* Tossed in `cache_info` while at it.
=> Chore prompts logs

.github/workflows/ci.yml, pins/__init__.py, requirements/minimum.txt, setup.cfg
* remove internal classes from init
* pin minimum dependency versions
- add entry to test matrix for checking minimum versions
=> refactor!: only keep high level functions in init

setup.cfg
=> fix: add requests as a dependency

pins/boards.py, pins/tests/test_boards.py
Addresses #108 
Note that I also fixed / included a test of pin_write setting access_type
=> fix(rsconnect): raise error if attempting to create content for other user

pins/boards.py, pins/rsconnect/html/index.html, pins/tests/_snapshots/test_board_pin_write_rsc_index_html/index.html
Partially address #114 , but adding a python code snippet for retrieving the pin.
=> Feat rsc code block

README.md, docs/getting_started.Rmd
=> remove todo notes around arrow

pins/tests/test_boards.py
* Fixes a cache test on windows CI, by sleeping between access times
=> tests: sleep in another cache test

pins/constructors.py, pins/tests/test_constructors.py
=> feat: cloud board_deparse

pins/boards.py
Minor fix to correctly display f-string.
=> fix: missing f for f-string

pins/rsconnect/api.py
=> fix(rsc): change http auth 'key' to 'Key'

pins/rsconnect/html/index.html, pins/tests/_snapshots/test_board_pin_write_rsc_index_html/index.html
Closes #145 
Related to rstudio/pins-r#690
=> Specify "Python Code" in Connect preview

README.Rmd, README.md, pins/constructors.py, pins/rsconnect/html/index.html, pins/tests/_snapshots/test_board_pin_write_rsc_index_html/index.html
* updates some remaining places to change RStudio -> Posit
* update HTML generated for Posit Connect pin index page to use `board_connect`
=> Docs posit connect

pins/constructors.py, pins/tests/test_constructors.py
Adding deparsing of `board_url` and `board_urls`
=> deparse url boards

.github/workflows/ci.yml
=> ci: add ci support for python 3.11

pins/boards.py, pins/tests/helpers.py, pins/tests/test_boards.py, pins/versions.py
=> support unversioned boards

setup.cfg
=> Add comment linking why we use appdirs in setup.cfg

docs/get_started.qmd
=> Add sentence in docs disclaiming against high frequency writes.

pins/tests/conftest.py, pins/tests/test_boards.py, pins/tests/test_cache.py, pins/tests/test_constructors.py, pins/tests/test_drivers.py
=> Replace tmp_dir2 fixture with tmp_path.

pins/_types.py, pins/boards.py, pins/cache.py, pins/config.py, pins/constructors.py, pins/drivers.py, pins/meta.py, pins/rsconnect/api.py, pins/rsconnect/fs.py, pins/tests/conftest.py, pins/tests/helpers.py, pins/tests/test_boards.py, pins/tests/test_cache.py, pins/tests/test_compat.py, pins/tests/test_compat_old_types.py, pins/tests/test_config.py, pins/tests/test_constructors.py, pins/tests/test_drivers.py, pins/tests/test_meta.py, pins/tests/test_rsconnect_api.py, pins/tests/test_utils.py, pins/tests/test_versions.py, pins/utils.py, pins/versions.py, pyproject.toml, script/ci-compat-check/dump_py_pins.py, script/ci-compat-check/validate_r_to_py.py, script/stage_example_bundle.py
=> Enable isort rules

pins/boards.py, pins/meta.py, pins/rsconnect/api.py, pins/tests/test_versions.py, pins/versions.py, pyproject.toml
To fix #281.
I also smuggled in the fix to #283, it felt wrong not to.
=> Fix bug where error message is missing info at the end

.github/workflows/ci.yml, Makefile
To fix Posit Connect tests failing with `Error: docker-compose command not found `
=> maint: update to v2 docker compose

pins/rsconnect/fs.py, pyproject.toml
=> Enable `reportIncompatibleVariableOverride` in pyright

.pre-commit-config.yaml, pins/rsconnect/api.py, pins/tests/test_rsconnect_api.py
=> Use correct endpoint for RsConnect get_user with guid

pins/cache.py, pins/constructors.py, pyproject.toml
=> Enable reportGeneralTypeIssues in pyright

pins/boards.py, pins/tests/test_boards.py
=> Fix bug in pin_versions_prune for days arg

pins/boards.py, pyproject.toml
=> Enable reportAssignmentType in pyright

pins/meta.py, pins/rsconnect/api.py, pyproject.toml
=> Enable reportIndexIssue in pyright

.env.dev, CONTRIBUTING.md, pins/boards.py, pins/meta.py, pins/rsconnect/api.py, pins/rsconnect/fs.py, pins/tests/test_boards.py
Post-rebrand a few years ago, it's probably time to change at least the user facing language from RStudio -> Posit 🙈
=> maint: change user facing language from RStudio to Posit
